### ISSUE TITLE
Change of behavior in returning strings

### ISSUE THREAD

**Issue by krosk** [mrijken/toml-cli#26]
Hello,

toml-cli is useful for pyproject configuration manipulation, such as customizing the package version of pyproject. An example is appending a string to a given pyproject.toml:
```
[project]
version = "1.0"
```
And in shell:
```
toml set --toml-path pyproject.toml project.version $(toml get --toml-path pyproject.toml project.version).dev12345
``` 

The change of behavior is the following

Shell command line:
```
$(toml get --toml-path pyproject.toml project.version)
```

In version 0.3.1:
returns without quotes
```
1.0
```

In version 0.4.0:
returns with quotes
```
"1.0"
```

Breaking the above command line after customization of pyproject.toml
```
[project]
version = "\"1.0\".dev12345"
```

**Comment by mrijken** [comment]
Thanx. It's fixed in release 0.4.2
